name: UltimateRifts
description: UltimateRifts
main: com.songoda.ultimaterifts.UltimateRifts
softdepend: [ HolographicDisplays, Vault, EpicHoppers, WorldEdit ]
version: maven-version-number
author: Songoda
api-version: 1.13

commands:
  ultimaterifts:
    description: View information on this plugin.
    default: true
    aliases: [ rift ]
    usage: /rift
