name: UltimateRifts
description: UltimateRifts
main: com.songoda.ultimaterifts.UltimateRifts
depend:
  - WorldEdit
softdepend:
  - HolographicDisplays
  - Vault
  - EpicHoppers
version: maven-version-number
author: Songoda
api-version: 1.13

commands:
  ultimaterifts:
    description: View information on this plugin.
    default: true
    aliases: [ rift ]
    usage: /rift
